# fly.toml file generated for zoviyo-backend

app = "zoviyo-backend"
primary_region = "sin" # Singapore region, you can change it

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
